# Generated by Django 2.0.7 on 2018-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(max_length=200, upload_to='course/%Y/%m', verbose_name='封面图'),
        ),
    ]
