# Generated by Django 2.0.7 on 2018-07-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='zl', max_length=24, verbose_name='用户名')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件地址')),
            ],
            options={
                'verbose_name': '用户数据表',
                'verbose_name_plural': '用户数据表',
                'db_table': 'user_table',
            },
        ),
    ]
